### ISSUE TITLE
error using torch2caffe

### ISSUE THREAD

**Issue by xiao1228** [facebook/fb-caffe-exts#5]
Hi, The code I use for convert the torch model to caffemodel is:
th torch2caffe/torch2caffe.lua --input /home/xiao/Documents/convNet-direct/torch-impl/sceneLabeling-own/results-own2model-full-singlescale/model.net --prototxt test.prototxt --caffemodel test.caffemodel 715 3 240 320

The error I received is this
Traceback (most recent call last):
  File "/home/xiao/Documents/fb-caffe-exts-master/torch2caffe/caffe_layers.py", line 278, in convert
    return converter[typename](torch_layer)
  File "/home/xiao/Documents/fb-caffe-exts-master/torch2caffe/caffe_layers.py", line 123, in spatial_convolution
    bias = torch_layer["bias"]
KeyError: u'bias'
/home/xiao/torch/install/bin/luajit: ./torch2caffe/lib.lua:162: Python error: opaque ref: call
Traceback (most recent call last):
  File "/home/xiao/Documents/fb-caffe-exts-master/torch2caffe/lib_py.py", line 135, in finalize
    opts)
  File "/home/xiao/Documents/fb-caffe-exts-master/torch2caffe/caffe_builder.py", line 27, in to_caffe
    opts, layer.typename, layer.torch_layer)
  File "/home/xiao/Documents/fb-caffe-exts-master/torch2caffe/caffe_layers.py", line 278, in convert
    return converter[typename](torch_layer)
  File "/home/xiao/Documents/fb-caffe-exts-master/torch2caffe/caffe_layers.py", line 123, in spatial_convolution
    bias = torch_layer["bias"]
KeyError: u'bias'

stack traceback:
    [C]: in function 'finalize'
    ./torch2caffe/lib.lua:162: in function 'convert'
    ./torch2caffe/lib.lua:168: in function 'main'
    torch2caffe/torch2caffe.lua:23: in main chunk
    [C]: in function 'dofile'
    ...xiao/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x00406670

Is it something wrong with the bias or what?Thank you

**Comment by okraus** [comment]
Hi, I'm getting the u'bias' key error as well for spatial_convolution layers
I pasted the output below.
@xiao1228, did you find any solutions / causes for this?

After looking more into my models, I think it's related to spatialBatchNormalization layers in the lua models.

Thanks

th> t2c.run(opts,model)
Running with model:  
nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> (15) -> (16) -> output](1): nn.SpatialConvolution(12 -> 32, 3x3, 1,1, 1,1)
  (2): nn.ReLU
  (3): nn.SpatialConvolution(32 -> 64, 3x3, 1,1, 1,1)
  (4): nn.ReLU
  (5): nn.SpatialConvolution(64 -> 64, 3x3, 1,1, 1,1)
  (6): nn.ReLU
  (7): nn.SpatialConvolution(64 -> 64, 3x3, 1,1, 1,1)
  (8): nn.ReLU
  (9): nn.SpatialConvolution(64 -> 100, 1x1)
  (10): nn.ReLU
  (11): nn.Dropout(0.500000)
  (12): nn.SpatialConvolution(100 -> 100, 1x1)
  (13): nn.ReLU
  (14): nn.Dropout(0.500000)
  (15): nn.SpatialConvolution(100 -> 1, 1x1)
  (16): nn.Sigmoid
}
INFO:torch2caffe.lib_py:added layer caffe.SpatialConvolution_0: bottom=[data], top=[caffe.SpatialConvolution_0]
INFO:torch2caffe.lib_py:added layer caffe.ReLU_1: bottom=[caffe.SpatialConvolution_0], top=[caffe.SpatialConvolution_0]
INFO:torch2caffe.lib_py:added layer caffe.SpatialConvolution_2: bottom=[caffe.SpatialConvolution_0], top=[caffe.SpatialConvolution_2]
INFO:torch2caffe.lib_py:added layer caffe.ReLU_3: bottom=[caffe.SpatialConvolution_2], top=[caffe.SpatialConvolution_2]
INFO:torch2caffe.lib_py:added layer caffe.SpatialConvolution_4: bottom=[caffe.SpatialConvolution_2], top=[caffe.SpatialConvolution_4]
INFO:torch2caffe.lib_py:added layer caffe.ReLU_5: bottom=[caffe.SpatialConvolution_4], top=[caffe.SpatialConvolution_4]
INFO:torch2caffe.lib_py:added layer caffe.SpatialConvolution_6: bottom=[caffe.SpatialConvolution_4], top=[caffe.SpatialConvolution_6]
INFO:torch2caffe.lib_py:added layer caffe.ReLU_7: bottom=[caffe.SpatialConvolution_6], top=[caffe.SpatialConvolution_6]
INFO:torch2caffe.lib_py:added layer caffe.SpatialConvolution_8: bottom=[caffe.SpatialConvolution_6], top=[caffe.SpatialConvolution_8]
INFO:torch2caffe.lib_py:added layer caffe.ReLU_9: bottom=[caffe.SpatialConvolution_8], top=[caffe.SpatialConvolution_8]
INFO:torch2caffe.lib_py:added layer caffe.Dropout_10: bottom=[caffe.SpatialConvolution_8], top=[caffe.SpatialConvolution_8]
INFO:torch2caffe.lib_py:added layer caffe.SpatialConvolution_11: bottom=[caffe.SpatialConvolution_8], top=[caffe.SpatialConvolution_11]
INFO:torch2caffe.lib_py:added layer caffe.ReLU_12: bottom=[caffe.SpatialConvolution_11], top=[caffe.SpatialConvolution_11]
INFO:torch2caffe.lib_py:added layer caffe.Dropout_13: bottom=[caffe.SpatialConvolution_11], top=[caffe.SpatialConvolution_11]
INFO:torch2caffe.lib_py:added layer caffe.SpatialConvolution_14: bottom=[caffe.SpatialConvolution_11], top=[caffe.SpatialConvolution_14]
ERROR:torch2caffe.caffe_layers:Exception on converting caffe.SpatialConvolution, {'weight_offset': 3456.0, 'output_offset': 2880000.0, 'dH': 1.0, 'padH': 1.0, 'kH': 3.0, 'nOutputPlane': 32.0, 'input_offset': 1080000.0, 'train': False, 'kW': 3.0, 'groups': 1.0, 'dW': 1.0, 'nInputPlane': 12.0, 'padW': 1.0}
Traceback (most recent call last):
  File "/home/okraus/torch/fb-caffe-exts/torch2caffe/caffe_layers.py", line 278, in convert
    return converter[typename](torch_layer)
  File "/home/okraus/torch/fb-caffe-exts/torch2caffe/caffe_layers.py", line 123, in spatial_convolution
    bias = torch_layer["bias"]
KeyError: u'bias'
./torch2caffe/lib.lua:162: Python error: opaque ref: call
Traceback (most recent call last):
  File "/home/okraus/torch/fb-caffe-exts/torch2caffe/lib_py.py", line 135, in finalize
    opts)
  File "/home/okraus/torch/fb-caffe-exts/torch2caffe/caffe_builder.py", line 27, in to_caffe
    opts, layer.typename, layer.torch_layer)
  File "/home/okraus/torch/fb-caffe-exts/torch2caffe/caffe_layers.py", line 278, in convert
    return converter[typename](torch_layer)
  File "/home/okraus/torch/fb-caffe-exts/torch2caffe/caffe_layers.py", line 123, in spatial_convolution
    bias = torch_layer["bias"]
KeyError: u'bias'

stack traceback:
    [C]: in function 'finalize'
    ./torch2caffe/lib.lua:162: in function 'convert'
    ./torch2caffe/lib.lua:168: in function 'run'
    [string "_RESULT={t2c.run(opts,model)}"]:1: in main chunk
    [C]: in function 'xpcall'
    /home/okraus/torch/install/share/lua/5.1/trepl/init.lua:650: in function 'repl'
    ...raus/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
    [C]: at 0x00406670

**Comment by gcr** [comment]
I had this issue too. It turns out that `fb.python` does not load CudaTensors, so the `bias` field of the `nn.Module` wasn't being populated at all.

The one-line fix is to convert the model to a CPU-only model. In `lib.lua` in the `M.convert` function, add
`torch_net:float()` at the beginning.

Now I get a different error, horray!

**Comment by KevinYuk** [comment]
Hi @gcr, are you sure we can directly convert torch_net to float? It seems that torch_net is a string type.
